#
# Steps for building and testing Jest. See jobs defined in .azure-pipelines.yml
#

steps:
  - checkout: self
    path: jest

  # Ensure Node.js 12 is active
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Use Node.js 12'

  # Ensure Python 2.7 is active
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
    displayName: 'Use Python 2.7'

  # Run yarn to install dependencies and build
  - script: node scripts/remove-postinstall
    displayName: 'Remove postinstall script'

  - task: CacheBeta@0
    inputs:
      key: yarn | $(Agent.OS) | yarn.lock
      path: $(YARN_CACHE_FOLDER)
    displayName: Cache Yarn packages

  - script: yarn install-no-ts-build
    displayName: 'Install dependencies'

  # Run test-ci-partial
  - script: yarn run test-ci-partial
    displayName: 'Run tests'

  # Publish CI test results
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/reports/junit/*.xml'
      testRunTitle: 'CI Tests $(Agent.OS)'
    displayName: 'Publish test results'
    condition: succeededOrFailed()
