language: node_js

node_js:
  - 'lts/*'

branches:
  only:
    - master

install: yarn --immutable

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

script:
  - yarn build:js
  - yarn run test-ci-partial
