language: node_js

node_js: 10

env:
  - YARN_GPG=no

sudo: false

os:
  - windows
  - linux


before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - if [[ $TRAVIS_OS_NAME == windows ]]; then
    choco install python2;
    export PATH="/c/Python27:/c/Python27/Scripts:$PATH";
    fi

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

script:
  - yarn run test-ci-partial
