
# Note: this file's config override the Netlify UI admin config

# production build
[build]
  base = "/"
  command = "yarn workspace jest-website netlify:ci:production"
  publish = "/website/build"

[build.environment]
  NODE_VERSION = "v14.17.0"
  NODE_OPTIONS = "--max_old_space_size=4096"

[context.production]
  # Do not build the site if there's no site-related changes
  ignore = "git diff --quiet HEAD^ HEAD -- website/ docs/ netlify.toml"

# deploy preview build (faster config)
[context.deploy-preview]
  command = "yarn workspace jest-website netlify:ci:deployPreview"


[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "website/node_modules/.cache",
    ]
