# Note: this file's config override the Netlify UI admin config

# production build
[build]
  base = "/"
  command = "yarn workspace jest-website netlify:ci:production"
  publish = "/website/build"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max_old_space_size=4096"
  # default cache
  YARN_ENABLE_GLOBAL_CACHE = "true"
  YARN_GLOBAL_FOLDER = "/opt/buildhome/.yarn_cache"
  YARN_CACHE_FOLDER = "/opt/buildhome/.yarn_cache"
  YARN_VERSION = "3.7.0"

[context.production]
  # Do not build the site if there's no site-related changes
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- website/ docs/ netlify.toml"

# deploy preview build (faster config)
[context.deploy-preview]
  command = "yarn workspace jest-website netlify:ci:deployPreview"

[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "website/node_modules/.cache",
    ]
