version: 2.1

aliases:
  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages
  - &install
    pkg-manager: yarn
    override-ci-command: yarn install --immutable && yarn build:js
    cache-path: ~/.yarn/berry/cache
    include-branch-in-cache-key: false
    app-dir: ~/jest

orbs:
  node: circleci/node@4.0.0

jobs:
  test-node:
    parameters:
      node-version:
        type: string
      partial:
        type: boolean
        default: false
    working_directory: ~/jest
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-npm: false
      - node/install-packages: *install
      - when:
          condition: << parameters.partial >>
          steps:
            - run:
                command: yarn test-ci-partial
      - unless:
          condition: << parameters.partial >>
          steps:
            - run:
                command: yarn test-ci
      - store_test_results:
          path: reports/junit

  test-jest-jasmine:
    working_directory: ~/jest
    executor: node/default
    steps:
      - checkout
      - node/install:
          lts: true
          install-npm: false
      - node/install-packages: *install
      - run:
          command: JEST_JASMINE=1 yarn test-ci-partial && JEST_JASMINE=1 yarn test-leak
      - store_test_results:
          path: reports/junit

# Workflows enables us to run multiple jobs in parallel
workflows:
  build-and-deploy:
    jobs:
      - test-node:
          matrix:
            parameters:
              node-version: ['14']
      - test-node:
          name: test-node-partial-<< matrix.node-version >>
          partial: true
          matrix:
            parameters:
              node-version: ['10', '12', '15', '16']
      - test-jest-jasmine
