aliases:
  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages
  - &install
    pkg-manager: yarn
    override-ci-command: yarn install --immutable && yarn build:js
    cache-path: ~/.yarn/berry/cache
    include-branch-in-cache-key: false
    app-dir: ~/jest

orbs:
  node: circleci/node@4.0.0
version: 2.1
jobs:
  test-node-10:
    working_directory: ~/jest
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '10'
          install-npm: false
      - node/install-packages: *install
      - run:
          command: yarn test-ci-partial
      - store_test_results:
          path: reports/junit

  test-jest-circus:
    working_directory: ~/jest
    executor: node/default
    steps:
      - checkout
      - node/install:
          lts: true
          install-npm: false
      - node/install-packages: *install
      - run:
          command: JEST_CIRCUS=1 yarn test-ci-partial && JEST_CIRCUS=1 yarn test-leak
      - store_test_results:
          path: reports/junit

  test-node-12:
    working_directory: ~/jest
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '12'
          install-npm: false
      - node/install-packages: *install
      - run:
          command: yarn test-ci-partial
      - store_test_results:
          path: reports/junit

  test-node-14:
    working_directory: ~/jest
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '14'
          install-npm: false
      - node/install-packages: *install
      - run:
          command: yarn test-ci
      - store_test_results:
          path: reports/junit

  test-node-15:
    working_directory: ~/jest
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '15'
          install-npm: false
      - node/install-packages: *install
      - run:
          command: yarn test-ci-partial
      - store_test_results:
          path: reports/junit

  test-or-deploy-website:
    working_directory: ~/jest
    executor: node/default
    resource_class: large
    steps:
      - checkout
      - node/install:
          lts: true
          install-npm: false
      - node/install-packages: *install
      - run:
          name: Test or Deploy Jest Website
          command: ./.circleci/website.sh

# Workflows enables us to run multiple jobs in parallel
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test-node-10
      - test-node-12
      - test-node-14
      - test-node-15 # current
      - test-jest-circus
      - test-or-deploy-website:
          filters: *filter-ignore-gh-pages
