aliases:
  - &restore-cache
    keys:
      - v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # Fallback in case checksum fails
      - v2-dependencies-{{ .Branch }}-

  - &save-cache
    paths:
      - node_modules
      - website/node_modules
    key: v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}

  - &filter-ignore-gh-pages
    branches:
      ignore: gh-pages
  - &install node scripts/remove-postinstall && yarn --no-progress --frozen-lockfile --ignore-engines && node scripts/build

version: 2
jobs:
  lint-and-typecheck:
    working_directory: ~/jest
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress --frozen-lockfile
      - save-cache: *save-cache
      - run: yarn lint --format junit -o reports/junit/js-lint-results.xml && yarn lint-es5-build --format junit -o reports/junit/js-es5-lint-results.xml  && yarn lint:md:ci && yarn check-copyright-headers
      - store_test_results:
          path: reports/junit

  test-node-6:
    working_directory: ~/jest
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: *install
      - save-cache: *save-cache
      - run:
          # react-native and react-testing-library do not work with node 6
          command: rm -rf examples/react-native examples/react-testing-library && yarn test-ci-partial
      - store_test_results:
          path: reports/junit

  test-node-8:
    working_directory: ~/jest
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: *install
      - save-cache: *save-cache
      - run:
          command: yarn test-ci-partial
      - store_test_results:
          path: reports/junit

  test-node-10:
    working_directory: ~/jest
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: *install
      - save-cache: *save-cache
      - run:
          command: yarn test-ci
      - store_test_results:
          path: reports/junit

  test-jest-circus:
    working_directory: ~/jest
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: *install
      - save-cache: *save-cache
      - run:
          command: JEST_CIRCUS=1 yarn test-ci-partial
      - store_test_results:
          path: reports/junit

  test-node-11:
    working_directory: ~/jest
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: *install
      - save-cache: *save-cache
      - run:
          command: yarn test-ci-partial
      - store_test_results:
          path: reports/junit

  test-browser:
    working_directory: ~/jest
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: *install
      - save-cache: *save-cache
      - run: yarn test-ci-es5-build-in-browser

  test-or-deploy-website:
    working_directory: ~/jest
    docker:
      - image: circleci/node:10
    resource_class: large
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: *install
      - save-cache: *save-cache
      - run:
          name: Test or Deploy Jest Website
          command: ./.circleci/website.sh

# Workflows enables us to run multiple jobs in parallel
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - lint-and-typecheck
      - test-node-6
      - test-node-8
      - test-node-10
      - test-jest-circus
      - test-node-11 # current
      - test-browser
      - test-or-deploy-website:
          filters: *filter-ignore-gh-pages
